### PR TITLE
Update test projects to NServiceBus 7.1

### PR DESCRIPTION
**Pull request by timbussmann**
Unable to switch to newer NUnit versions though because of https://github.com/nunit/nunit/issues/2684

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Are we going to move forward with 7.1 or hold off for 7.2?

**Comment by danielmarbach** [comment]
Build is failing with the fullname filter issue. I think we got a workaround by the NUnit folks. Happy to look into it this week

**Comment by SeanFeldman** [comment]
> Build is failing with the fullname filter issue.

Mind to share a link or short description? Thanks.

**Comment by danielmarbach** [comment]
@seanfeldman the link is in the description of the issue. TLDR; We probably have to rewrite a large portion if the run tests in the cluster infrastructure because things have been made internal or moved

**Comment by timbussmann** [comment]
so what's the decision here? Shall we close this PR and not update due to the NUnit issues?

**Comment by timbussmann** [comment]
I've raised an issue here: https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/issues/74
Closing this PR for now.

**Pull request closed without merging**
