### PR TITLE
New csproj2

### PR DESCRIPTION
**Pull request by SimonCropp**
Connects to Particular/NServiceBus.Azure#302

### CODE REVIEW

**Comment by SimonCropp** [comment]
@danielmarbach any ideas why this is failing?

**Comment by danielmarbach** [comment]
@SimonCropp pushed an update. Let's keep the fingers crossed

**Comment by SimonCropp** [comment]
@danielmarbach still the same error

**Comment by danielmarbach** [comment]
Will try to hunt this down if I can tomorrow

**Comment by danielmarbach** [comment]
@SimonCropp I had a hunch the failing is related to how the solution is compiled and deployed with the default compile target. Since VS automatically added AnyCPU I tried to revert it to x64 to enforce x64 target compilation (like we originally did, we got rid of AnyCPU since it did not really work)

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers anyone have ideas on the error we r getting in TC?

**Comment by SimonCropp** [comment]
@danielmarbach i am willing to abandon this effort. and hope that SF proved better support for the new project system in the future

**Comment by danielmarbach** [comment]
There seems to be an SDK update around the corner. Should we mark this WIP and let it stay open until then or close and reopen a new PR when ready?

**Comment by SimonCropp** [comment]
happy to leave open. although i would lead towards `[BLOCKED]` rather than `[WIP]`

**Comment by yvesgoeleven** [comment]
I marked the parent issue (https://github.com/Particular/NServiceBus.Azure/issues/302) as blocked as well

**Comment by SeanFeldman** [comment]
Moving it into `Blocked` if it's such /cc @yvesgoeleven

**Comment by danielmarbach** [comment]
@seanfeldman the root cause is solved. I will check in the approved file tomorrow and inspect the last failing ATT. Then this should be good to go

**Comment by yvesgoeleven** [comment]
@SeanFeldman after daniel mentioned the root cause, I had move it back to progress, but indeed forgot to remove the text

**Comment by danielmarbach** [comment]
Green!

**Pull request merged**
