### PR TITLE
Hotfix 1.0.1

### LINKED ISSUE #59: ServiceFabric Persistence Outbox Cleanup queue grows indefinitely
## Who's affected

- All users using the Service Fabric Persistence in combination with the Outbox

## Symptoms

Service Fabric outbox cleanup does a best effort to clean up the oldest entries first. It does that by pushing the cleanup command to a reliable queue and uses a background operation to clear the outbox reliable dictionary. The cleanup command queue is only iterated over but never cleared. This leads to an ever-growing cleanup queue.

## Reproduction test

```
[Test]
public async Task Should_clear_dispatched_messages_and_cleanup_queue_after_given_expiry()
{
    configuration.RequiresOutboxSupport();

    var storage = (OutboxStorage)configuration.OutboxStorage;
    var ctx = configuration.GetContextBagForOutbox();

    var messageId = Guid.NewGuid().ToString();

    var messageToStore = new OutboxMessage(messageId, new[] { new TransportOperation("x", null, null, null) });
    using (var transaction = await storage.BeginTransaction(ctx))
    {
        await storage.Store(messageToStore, transaction, ctx);

        await transaction.Commit();
    }

    // Account for the low resolution of DateTime.UtcNow.
    var afterStore = DateTimeOffset.UtcNow.AddTicks(1);

    await storage.SetAsDispatched(messageId, configuration.GetContextBagForOutbox());

    await configuration.CleanupMessagesOlderThan(afterStore);

    var message = await storage.Get(messageId, configuration.GetContextBagForOutbox());
    using (var tx = stateManager.CreateTransaction())
    {
        Assert.AreEqual(0, await storage.Cleanup.GetCountAsync(tx));
        Assert.AreEqual(0, await storage.Outbox.GetCountAsync(tx));
    }
    Assert.Null(message);
}
```

### PR DESCRIPTION
**Pull request by danielmarbach**
Fixes #59

### CODE REVIEW

**Comment by danielmarbach** [comment]
@SeanFeldman can you review? Happy to walk you through in a call if necessary.

**Comment by SeanFeldman** [comment]
This hotfix would need to go into `develop` as well.

**Comment by danielmarbach** [comment]
Thanks for reminding us. We have it as a PoA point

Am 17.02.2018 00:23 schrieb "Sean Feldman" <notifications@github.com>:

This hotfix would need to go into develop as well.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Particular/NServiceBus.Persistence.ServiceFabric/pull/60#issuecomment-366387449>,
or mute the thread

**Comment by Scooletz** [comment]
Looks Awesome To Me 😍 @danielmarbach

**Pull request merged**
