### PR TITLE
Remove gateway deduplication from component tests persistence configuration

### PR DESCRIPTION
**Pull request by mauroservienti**

### CODE REVIEW

**Comment by mauroservienti** [comment]
Sounds like this is failing because of the ServiceFabric SDK version on build agents.

**Comment by danielmarbach** [comment]
@mauroservienti that is weird because I recently updated to the latest versions (roughly 3 weeks ago) has someone done a restore of a build agent that could cause this?

**Comment by mauroservienti** [comment]
In 3 weeks? I don't think so. Some of the agents were restored to fix a TC integration error while in Mexico.

But I'm not sure if the build failure is due to that, even if a type load exception on one of SDK types points in that direction.

**Comment by danielmarbach** [comment]
I updated the agents before mexico... So that explains it. Because before that the SF builds were all green

**Pull request merged**
