### PR TITLE
Initial structure with two projects

### PR DESCRIPTION
**Pull request by Scooletz**
Initial project structure

### CODE REVIEW

**Comment by adamralph** [comment]
Given this is a completely new project, what are the thoughts on using the "standard" .NET layout defined at https://gist.github.com/davidfowl/ed7564297c61fe9ab814 ? Most of the external OSS projects I work on now use this.

**Comment by tmasternak** [comment]
@adamralph I'm reluctant to use it for now. Here are my arguments:
 1. It's different from other repositories
 2. Things like build scripts, docs and samples will either not exists or will be in doco repositories.

**Comment by yvesgoeleven** [comment]
@tmasternak agreed, all of our tooling is based on current conventions. doing something else will be painfull

**Comment by adamralph** [comment]
> It's different from other repositories

I don't think this is necessarily a bad thing. We should take care not to cargo-cult and we should have an outlet for fail small, learn big.

> Things like build scripts, docs and samples will either not exists or will be in doco repositories.

All of the folders listed in the gist are opt-in. The idea is to pick and choose what makes sense for your repo, but not to deviate from that layout, e.g. solution should be in root, test projects should be under `test`, etc.

> ...all of our tooling is based on current conventions. doing something else will be painfull

Sadly, I have to agree. It's something I'd like to challenge, but it's a thread best continued elsewhere.

Overall, I understand the reasoning to go with the current convention here and I don't want to hijack this work. I'll raise the general point elsewhere. 👍

**Pull request merged**
