### PR TITLE
Update SF lib dependencies to 2.7.198 and 5.7.198

### PR DESCRIPTION
**Pull request by danielmarbach**
Build agents are updated

### CODE REVIEW

**Comment by SimonCropp** [comment]
Why not wildcards?

**Comment by danielmarbach** [comment]
So far we have not yet seen any documentation or anything confirming that MS actually follows a sane versioning semantic with the SDK. I might be wrong. @Particular/azure-maintainers thoughts? Happy to reach out over github and nagg the team

**Comment by SeanFeldman** [comment]
I've raised the question on the advisory board.

**Comment by SimonCropp** [comment]
@SeanFeldman my question should not block this PR

**Comment by SeanFeldman** [comment]
Simon, my comment was not blocking.

**Pull request merged**
